events {}

http {
    server {
        # Nginx écoute sur le port 8080 à l'intérieur de son conteneur
        listen 8080;

        location / {
            # Il redirige tout le trafic vers le service backend sur le port 5000.
            # Docker Compose est assez intelligent pour distribuer ça sur les 3 conteneurs !
            proxy_pass http://lab-docker-back-service:5000;
        }
    }
}