# Port d'écoute du serveur
server.port = 80

# Dossier contenant vos fichiers HTML (document root)
server.document-root = "/var/www/html"

# Fichier à charger par défaut quand on arrive sur le site
index-file.names = ( "index.html" )

# Définition des types de fichiers de base pour que le navigateur les comprenne
mimetype.assign = (
  ".html" => "text/html", 
  ".txt"  => "text/plain",
  ".css"  => "text/css",
  ".js"   => "text/javascript",
  ".png"  => "image/png",
  ".jpg"  => "image/jpeg"
)